# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'ToDoDaily' do
  platform :ios, '13.0'

  use_frameworks!
  inhibit_all_warnings!

  # Pods for ToDoDaily
 pod 'SwiftGen'
 pod 'Firebase/Auth'
 pod 'GoogleSignIn'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
